### ISSUE TITLE
Error enriching Phabricator with elasticgirl.15

### ISSUE THREAD

**Issue by sanacl** [grimoirelab/GrimoireELK#102]
I've found the following error while trying to analyze a Phabricator (Maniphest) instance with the release elasticgirl.15

```
2017-09-15 18:15:43,690 - urllib3.connectionpool - DEBUG - https://alexandria.****:443 "POST /data/maniphest_bitergia_170915/_search?scroll=10m&size=1000 HTTP/1.1" 200 26668191
2017-09-15 18:15:45,160 - grimoire_elk.arthur - ERROR - Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 522, in enrich_backend
    enrich_count = enrich_items(ocean_backend, enrich_backend)
  File "./grimoire_elk/arthur.py", line 287, in enrich_items
    total= enrich_backend.enrich_items(ocean_backend)
  File "./grimoire_elk/elk/enrich.py", line 344, in enrich_items
    rich_item = self.get_rich_item(item)
  File "./grimoire_elk/elk/phabricator.py", line 249, in get_rich_item
    self.__fill_phab_ids(item['data'])
  File "./grimoire_elk/elk/phabricator.py", line 235, in __fill_phab_ids
    self.phab_ids_names[item['fields']['ownerData']['phid']] = item['fields']['ownerData']['userName']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by acs** [comment]
Fixed in https://github.com/grimoirelab/GrimoireELK/commit/cf304f9b5526aa151d2b42df20d334283715b761
