### ISSUE TITLE
p2o.py github backend: issue with reactions

### ISSUE THREAD

**Issue by assadOW2** [grimoirelab/GrimoireELK#112]
When fetching issues from github I have the follwing issue:
_Error feeding ocean from github (https://github.com/elastic/logstash): 'reactions'_

I am using latest version of GrimoireLab, elasticgirl 18.1 

Here is complete log from terminal:

```
(grimoireelk) assadm@assadm-ThinkPad-T470p:~$ p2o.py --enrich --index github_raw --index-enrich github -e http://localhost:9200 --no_inc --debug   github elastic logstash --from-date '2017-01-01' --sleep-for-rate
2017-10-25 14:13:58,035 Debug mode activated
2017-10-25 14:13:58,041 Feeding Ocean from github (https://github.com/elastic/logstash)
2017-10-25 14:13:58,126 Incremental from: 2017-01-01 00:00:00+00:00
2017-10-25 14:13:58,127 Get GitHub paginated items from https://api.github.com/repos/elastic/logstash/issues
2017-10-25 14:13:59,081 Rate limit: 59
2017-10-25 14:13:59,083 Page: 1/89
2017-10-25 14:13:59,246 Getting info for https://api.github.com/users/thmoeller
2017-10-25 14:13:59,651 Rate limit: 58
2017-10-25 14:14:00,036 Rate limit: 57
2017-10-25 14:14:00,152 Get GitHub paginated items from https://api.github.com/repos/elastic/logstash/issues/5116/comments
2017-10-25 14:14:00,614 Rate limit: 56
2017-10-25 14:14:00,660 Getting info for https://api.github.com/users/ph
2017-10-25 14:14:01,049 Rate limit: 55
2017-10-25 14:14:01,507 Rate limit: 54
2017-10-25 14:14:01,585 Error feeding ocean from github (https://github.com/elastic/logstash): 'reactions'
Traceback (most recent call last):
  File "/home/assadm/venvs/grimoireelk/lib/python3.5/site-packages/grimoire_elk/arthur.py", line 126, in feed_backend
    ocean_backend.feed(from_date)
  File "/home/assadm/venvs/grimoireelk/lib/python3.5/site-packages/grimoire_elk/ocean/elastic.py", line 201, in feed
    for item in items:
  File "/home/assadm/venvs/grimoireelk/lib/python3.5/site-packages/perceval/backend.py", line 360, in decorator
    for data in func(self, *args, **kwargs):
  File "/home/assadm/venvs/grimoireelk/lib/python3.5/site-packages/perceval/backends/core/github.py", line 175, in fetch
    issue[field + '_data'] = self.__get_issue_comments(issue['number'])
  File "/home/assadm/venvs/grimoireelk/lib/python3.5/site-packages/perceval/backends/core/github.py", line 280, in __get_issue_comments
    self.__get_issue_comment_reactions(comment_id, comment['reactions']['total_count'])
KeyError: 'reactions'
2017-10-25 14:14:01,588 Adding repo to Ocean http://localhost:9200/conf/repos/github_raw_https:__github.com_elastic_logstash {'index': 'github_raw', 'success': False, 'repo_update': '2017-10-25T14:14:01.588240', 'backend_params': ['elastic', 'logstash', '--from-date', '2017-01-01', '--sleep-for-rate'], 'project': None, 'repo_update_start': '2017-10-25T14:13:58.125662', 'error': "'reactions'", 'index_enrich': 'github', 'backend_name': 'github'}
2017-10-25 14:14:01,669 Done github 
2017-10-25 14:14:01,669 Backed feed completed
fatal: Not a git repository (or any of the parent directories): .git
2017-10-25 14:14:01,699 Can't get the gelk version. /home/assadm/venvs/grimoireelk/lib/python3.5/site-packages/grimoire_elk/elk/enrich.py
2017-10-25 14:14:01,739 Last enrichment: None
2017-10-25 14:14:01,749 Adding enrichment data to http://localhost:9200/github
2017-10-25 14:14:01,750 Adding items to http://localhost:9200/github/items/_bulk (in 1000 packs)
2017-10-25 14:14:01,750 Creating a elastic items generator.
2017-10-25 14:14:01,750 http://localhost:9200/github_raw/_search?scroll=10m&size=100
{
    "query": {
        "bool": {
            "must": [
                {
                    "term": {
                        "origin": "https://github.com/elastic/logstash"
                    }
                }
            ]
        }
    },
    "sort": {
        "metadata__timestamp": {
            "order": "asc"
        }
    }
}
2017-10-25 14:14:01,767 No results found from http://localhost:9200/github_raw
2017-10-25 14:14:01,767 Updating GitHub users geolocations in Elastic
2017-10-25 14:14:01,767 Adding geoloc to http://localhost:9200/github/geolocations/_bulk (in 1000 packs)
2017-10-25 14:14:01,769 Adding geoloc to ES Done
2017-10-25 14:14:01,769 Total items enriched 0 
2017-10-25 14:14:01,769 Done github 
2017-10-25 14:14:01,770 Enrich backend completed
2017-10-25 14:14:01,770 Finished in 0.06 min
```

**Comment by valeriocos** [comment]
Hi @assadOW2, thanks for reporting this issue.
A similar issue was reported yesterday (https://github.com/grimoirelab/perceval/issues/187). If you use a token, you should be able to get reactions data.

**Comment by assadOW2** [comment]
Thanks for the quick reply.
It worked fine for me with the token.
