### ISSUE TITLE
[enrich] Getting the following error with Meetup items

### ISSUE THREAD

**Issue by albertinisg** [grimoirelab/GrimoireELK#119]
Using `elasticgirl.19` release, I'm getting the following error:
```bash
2017-11-08 10:43:41,105 - grimoire_elk.arthur - ERROR - Traceback (most recent call last):
  File "./grimoire_elk/arthur.py", line 486, in enrich_backend
    enrich_count = enrich_items(ocean_backend, enrich_backend)
  File "./grimoire_elk/arthur.py", line 301, in enrich_items
    total= enrich_backend.enrich_items(ocean_backend)
  File "./grimoire_elk/elk/meetup.py", line 326, in enrich_items
    super(MeetupEnrich, self).enrich_items(ocean_backend)
  File "./grimoire_elk/elk/enrich.py", line 376, in enrich_items
    rich_item = self.get_rich_item(item)
  File "./grimoire_elk/elk/enrich.py", line 80, in decorator
    eitem = func(self, *args, **kwargs)
  File "./grimoire_elk/elk/meetup.py", line 168, in get_rich_item
    eitem['time_date'] = unixtime_to_datetime(event['time']/1000).isoformat()
KeyError: 'time'
```

**Comment by acs** [comment]
A pretty strange error. Probably it is related to the phab version.

In which environment has this error appeared?

**Comment by acs** [comment]
Fixed in https://github.com/grimoirelab/GrimoireELK/commit/cf5dbbfcbff9c170d0c74a3b76dd3e9fe6bdf178

@albertinisg could you review it and close the ticket?

**Comment by zhquan** [comment]
The fix works
