### ISSUE TITLE
grimoire-kidash pip package not working

### ISSUE THREAD

**Issue by acs** [grimoirelab/GrimoireELK#137]
Trying to use the pip package grimoire-kidash:

```
kidash.py 
```

```
Traceback (most recent call last):
  File "/usr/local/bin/kidash.py", line 4, in <module>
    __import__('pkg_resources').run_script('grimoire-kidash==0.22.1', 'kidash.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'grimoire-elk==0.22.1' distribution was not found and is required by grimoire-kidash
```

**Comment by jgbarah** [comment]
Hmmm. How did you install that package? See what I find:

```bash
$ python3 -m venv /tmp/tests
$ source /tmp/tests/bin/activate
(tests) $ pip install grimoire-kidash
...
(tests) $ $ kidash.py
usage: usage: kidash [options]
kidash.py: error: --export or --import or --list needed
```

So, it seems to work...

**Comment by acs** [comment]
Doing the same but before installing grimoire-elk:

```
(acs@dellx) ~ $ python3 -m venv /tmp/tests
(acs@dellx) ~ $ source /tmp/tests/bin/activate
(acs@dellx) ~ $ pip install grimoire-elk
(acs@dellx) ~ $ pip install grimoire-kidash
(acs@dellx) ~ $ kidash.py 
usage: usage: kidash [options]
kidash.py: error: --export or --import or --list needed
```

Ups, it seems it was an issue with my local config!

I am sorry about the noise. Closing this issue.
