### ISSUE TITLE
Error when trying to install dependencies for p2o

### ISSUE THREAD

**Issue by jgbarah** [grimoirelab/GrimoireELK#17]
When trying to run p2o (just up to the point of showing the --help output) I don't see how to fulfill the dependency on MySQLdb:

```
$ python3 ./p2o.py --help
Traceback (most recent call last):
  File "./p2o.py", line 31, in <module>
    from grimoire.arthur import feed_backend, enrich_backend
  File "/home/jgb/src/grimoirelab/GrimoireELK/utils/grimoire/arthur.py", line 34, in <module>
    from grimoire.utils import get_elastic
  File "/home/jgb/src/grimoirelab/GrimoireELK/utils/grimoire/utils.py", line 49, in <module>
    from grimoire.elk.bugzilla import BugzillaEnrich
  File "/home/jgb/src/grimoirelab/GrimoireELK/utils/grimoire/elk/bugzilla.py", line 32, in <module>
    from .enrich import Enrich
  File "/home/jgb/src/grimoirelab/GrimoireELK/utils/grimoire/elk/enrich.py", line 28, in <module>
    import MySQLdb
ImportError: No module named 'MySQLdb'
```

But AFAIK, MySQLdb cannot be installed for Python3 ([see this question in StackOverflow](http://stackoverflow.com/questions/20049590/pip-3-3-install-mysql-python)). And in fact, when I try to install MySQL-python, I get errors that I cannot solve. I can install PyMySQL, but it seems that p2o is looking specifically for MySQLdb. So, what can I do?

**Comment by acs** [comment]
You can take a look at how we are installing it in GELK Docker image:

https://github.com/grimoirelab/GrimoireELK/blob/master/docker/gelk-arthur/Dockerfile#L37

**Comment by jgbarah** [comment]
So, the next install makes the trick:

```
pip3 install mysqlclient
``` 

Thanks a lot!
