### ISSUE TITLE
'GitHubCommand' object has no attribute 'offset'

### ISSUE THREAD

**Issue by mlem** [grimoirelab/GrimoireELK#39]
Hi,

I'm trying to import a simple project with your tool to see some git/github statistics.
I was following your guide at https://github.com/grimoirelab/use_cases/tree/master/documentfoundation

I can't import a simple git repo form github into elasticsearch because of the index creation. Something is not working out. 
Do you have some experience with this issue or can you hint me to the place where you are creating the index in your code?

```bash
bitergia@1cd265275072:~/GrimoireELK/utils$ ./p2o.py -e http://elasticsearch:9200 --index git_TDF -g git https://github.com/mlem/bankaustria-trend-analyzer.git --from-date "2014-01-01"
2016-07-21 08:32:17,507 Debug mode activated
2016-07-21 08:32:17,513 Feeding Ocean from git (https://github.com/mlem/bankaustria-trend-analyzer.git)
2016-07-21 08:32:17,714 Created index http://elasticsearch:9200/git_tdf
2016-07-21 08:32:17,851 Error creating ES mappings {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"malformed mapping no root object found"}],"type":"mapper_parsing_exception","reason":"malformed mapping no root object found"},"status":400}
2016-07-21 08:32:17,940 Error feeding ocean from git (https://github.com/mlem/bankaustria-trend-analyzer.git): 'GitCommand' object has no attribute 'offset'
2016-07-21 08:32:17,940 Adding repo to Ocean http://elasticsearch:9200/conf/repos/git_tdf_https:__github.com_mlem_bankaustria-trend-analyzer.git {'backend_params': ['https://github.com/mlem/bankaustria-trend-analyzer.git', '--from-date', '2014-01-01'], 'error': "'GitCommand' object has no attribute 'offset'", 'repo_update_start': '2016-07-21T08:32:17.940200', 'index_enrich': None, 'repo_update': '2016-07-21T08:32:17.940496', 'backend_name': 'git', 'success': False, 'index': 'git_TDF', 'project': None}
2016-07-21 08:32:17,985 Done git 
2016-07-21 08:32:17,989 Queued feed_backend job
2016-07-21 08:32:17,990 <Job 80587e61-314b-46fa-bff4-d8f44885d4a1: grimoire.arthur.feed_backend('http://elasticsearch:9200', False, False, 'git', ['https://github.com/mlem/bankaustria-trend-analyzer.git', '--from-date', '2014-01-01', '-t', '24df6490c0d8b4e7d474c492fe9872829770e5e2'], 'git_TDF', None, None)>
2016-07-21 08:32:17,990 Finished in 0.01 min
```
Error on elasticsearch_1:
```bash
elasticsearch_1 | [2016-07-21 08:24:33,187][DEBUG][action.admin.indices.mapping.put] [Korath the Pursuer] failed to put mappings on indices [[git_tdf]], type [items]
elasticsearch_1 | MapperParsingException[malformed mapping no root object found]
elasticsearch_1 | 	at org.elasticsearch.index.mapper.DocumentMapperParser.extractMapping(DocumentMapperParser.java:208)
elasticsearch_1 | 	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:93)
elasticsearch_1 | 	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:435)
elasticsearch_1 | 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:257)
elasticsearch_1 | 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230)
elasticsearch_1 | 	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:458)
elasticsearch_1 | 	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:762)
elasticsearch_1 | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
elasticsearch_1 | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
elasticsearch_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
elasticsearch_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
elasticsearch_1 | 	at java.lang.Thread.run(Thread.java:745)
```

from elastic search server the reponse to conf/repos
```json
{
  "took": 11,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 1,
    "hits": [
      {
        "_index": "conf",
        "_type": "repos",
        "_id": "git_tdf_https:__github.com_mlem_bankaustria-trend-analyzer",
        "_score": 1,
        "_source": {
          "error": "'GitHubCommand' object has no attribute 'offset'",
          "success": false,
          "repo_update_start": "2016-07-20T15:24:04.965358",
          "backend_params": [
            "--owner",
            "mlem",
            "--repository",
            "bankaustria-trend-analyzer",
            "--from-date",
            "2014-01-01"
          ],
          "index_enrich": null,
          "index": "git_tdf",
          "backend_name": "github",
          "project": null,
          "repo_update": "2016-07-20T15:24:04.965715"
        }
      },
      {
        "_index": "conf",
        "_type": "repos",
        "_id": "git_tdf_https:__github.com_mlem_bankaustria-trend-analyzer.git",
        "_score": 1,
        "_source": {
          "backend_params": [
            "https://github.com/mlem/bankaustria-trend-analyzer.git",
            "--from-date",
            "2014-01-01"
          ],
          "error": "'GitCommand' object has no attribute 'offset'",
          "repo_update_start": "2016-07-21T08:32:17.940200",
          "index_enrich": null,
          "repo_update": "2016-07-21T08:32:17.940496",
          "backend_name": "git",
          "success": false,
          "index": "git_TDF",
          "project": null
        }
      }
    ]
  }
}
```

**Comment by acs** [comment]
Fix already in master from this morning:

https://github.com/grimoirelab/GrimoireELK/commit/064cc0c4c882f5548513936f1608926fda6f4d09

Could you upgrade?

Thanks!
