### ISSUE TITLE
Missing module 'sortinghat'

### ISSUE THREAD

**Issue by jsmanrique** [grimoirelab/GrimoireELK#66]
I've tried to use p2o without Sorting Hat, and I get this error message:
```
python3 p2o.py --enrich --index git_yarn -e http://localhost:9200 --no_inc --debug git https://github.com/yarnpkg/yarn.git
Traceback (most recent call last):
  File "p2o.py", line 31, in <module>
    from grimoire.arthur import feed_backend, enrich_backend
  File "/home/jsmanrique/devel/GrimoireELK/utils/grimoire/arthur.py", line 35, in <module>
    from grimoire.utils import get_elastic
  File "/home/jsmanrique/devel/GrimoireELK/utils/grimoire/utils.py", line 59, in <module>
    from grimoire.elk.git import GitEnrich
  File "/home/jsmanrique/devel/GrimoireELK/utils/grimoire/elk/git.py", line 34, in <module>
    from grimoire.elk.sortinghat import SortingHat
  File "/home/jsmanrique/devel/GrimoireELK/utils/grimoire/elk/sortinghat.py", line 30, in <module>
    from sortinghat import api
ImportError: No module named 'sortinghat'
```

**Comment by acs** [comment]
Fixed in https://github.com/grimoirelab/GrimoireELK/commit/e99971cffdf49909ba6648137be37cbbf9cc4e34
